spring:
  server:
    thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      encoding: UTF-8
      mode: HTML5
      property: name="concurrent" value="false"
  tomcat:
    max-http-header-size: 65536
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sakila?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 0988771596
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: 
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
      timeout: 5000
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: tw.pan.mappers
server:
  port: 80
logging:
  level:
    tw.pan.mappers: debug
  org: 
    springframework:
      data:
        redis: debug
    fasterxml:
      jackson:
        databind: debug

    