# .github/workflows/translate.yml
name: Translate Readme

on:
    push:
        branches: ['**']

jobs:
    translate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 3
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.9'

            - name: Install dependencies
              run: |
                pip install -r aphra/requirements.txt

            - name: Auto Translate
              uses: Lin-jun-xiang/action-translate-readme@v2 # Based on the tag
              with:
                token: ${{ secrets.Action_Bot }} # Based on step2 name
                langs: "en,zh-TW,zh-CN,French,Arabic" # You can define any langs
